/// 🏢 Structure hiérarchique des assurances
/// 
/// Hiérarchie: Super Admin → Admin Compagnie → Admin Agence → Agents

class CompagnieAssurance {
  final String id;
  final String nom;
  final String logo;
  final String adresse;
  final String telephone;
  final String email;
  final String adminCompagnieId; // ID de l';      id: map['id'] ?? '';      nom: map['nom'] ?? '';      logo: map['logo'] ?? '';      adresse: map['adresse'] ?? '';      telephone: map['telephone'] ?? '';      email: map['email'] ?? '';      adminCompagnieId: map['adminCompagnieId'] ?? '';      dateCreation: DateTime.fromMillisecondsSinceEpoch(map['dateCreation';      active: map['active';      metadata: Map<String, dynamic>.from(map['metadata';      'id';      'nom';      'logo';      'adresse';      'telephone';      'email';      'adminCompagnieId';      'dateCreation';      'active';      'metadata';  final String adminAgenceId; // ID de l';      id: map['id'] ?? '';      compagnieId: map['compagnieId'] ?? '';      nom: map['nom'] ?? '';      adresse: map['adresse'] ?? '';      ville: map['ville'] ?? '';      gouvernorat: map['gouvernorat'] ?? '';      telephone: map['telephone'] ?? '';      email: map['email'] ?? '';      adminAgenceId: map['adminAgenceId'] ?? '';      dateCreation: DateTime.fromMillisecondsSinceEpoch(map['dateCreation';      active: map['active';      metadata: Map<String, dynamic>.from(map['metadata';      'id';      'compagnieId';      'nom';      'adresse';      'ville';      'gouvernorat';      'telephone';      'email';      'adminAgenceId';      'dateCreation';      'active';      'metadata';      id: map['id'] ?? '';      email: map['email'] ?? '';      nom: map['nom'] ?? '';      prenom: map['prenom'] ?? '';      telephone: map['telephone'] ?? '';        (e) => e.toString() == 'AdminType.${map['type']}';      compagnieId: map['compagnieId';      agenceId: map['agenceId';      dateCreation: DateTime.fromMillisecondsSinceEpoch(map['dateCreation';      active: map['active';      permissions: Map<String, dynamic>.from(map['permissions';      'id';      'email';      'nom';      'prenom';      'telephone';      'type': type.toString().split('.';      'compagnieId';      'agenceId';      'dateCreation';      'active';      'permissions';  final String? adminTraitantId; // ID de l';      id: map['id'] ?? '';      nom: map['nom'] ?? '';      prenom: map['prenom'] ?? '';      email: map['email'] ?? '';      telephone: map['telephone'] ?? '';      cin: map['cin'] ?? '';      compagnieId: map['compagnieId'] ?? '';      agenceId: map['agenceId'] ?? '';      documentUrl: map['documentUrl';      dateCreation: DateTime.fromMillisecondsSinceEpoch(map['dateCreation';        (e) => e.toString() == 'StatutDemande.${map['statut']}';      adminTraitantId: map['adminTraitantId';      dateTraitement: map['dateTraitement';        ? DateTime.fromMillisecondsSinceEpoch(map['dateTraitement';      commentaire: map['commentaire';      'id';      'nom';      'prenom';      'email';      'telephone';      'cin';      'compagnieId';      'agenceId';      'documentUrl';      'dateCreation';      'statut': statut.toString().split('.';      'adminTraitantId';      'dateTraitement';      'commentaire';